---
- name: Provision audio-validation laboratory runner
  hosts: audio_validation
  become: true
  roles:
    - common
    - audio_validation
    - github_runner

- name: Provision audio-target laboratory controller
  hosts: audio_target
  become: true
  roles:
    - common
    - audio_target
    - github_runner
