#!/usr/bin/env python3
"""Generate the single-source hosted resource baseline and its Markdown view."""

from __future__ import annotations

import argparse
import json
import tempfile
from pathlib import Path


def build(full: int, low: int, tiny: int, raw: int, runtime_full: int, runtime_tiny: int) -> dict:
    values = [full, low, tiny, raw, runtime_full, runtime_tiny]
    if any(value <= 0 for value in values):
        raise ValueError("resource measurements must be positive")
    if not (raw < tiny < low < full):
        raise ValueError("pipeline measurements must satisfy RAW < TINY < LOW < FULL")
    if not runtime_tiny < runtime_full:
        raise ValueError("runtime TINY must be smaller than runtime FULL")
    return {
        "schema_version": 1,
        "measurement_profile": "hosted-gcc-release",
        "pipeline_state_bytes": {
            "full": full,
            "low": low,
            "tiny": tiny,
            "raw": raw,
        },
        "runtime_state_bytes": {
            "full": runtime_full,
            "tiny": runtime_tiny,
        },
    }


def markdown(doc: dict) -> str:
    p = doc["pipeline_state_bytes"]
    r = doc["runtime_state_bytes"]
    return f"""# Generated Hosted Resource Baseline

This file is generated by `scripts/resource_baseline.py` from the hosted GCC Release resource-gate measurement. Do not edit the numeric values by hand in other documentation.

These values are hosted build-contract measurements. They are **not ABI constants, target-board RAM claims, CPU claims, or product-certification evidence**.

## Pipeline state

| Build envelope | Bytes |
| --- | ---: |
| FULL | {p['full']:,} |
| LOW | {p['low']:,} |
| TINY | {p['tiny']:,} |
| RAW / resampler-only | {p['raw']:,} |

## Linux runtime state

| Build envelope | Bytes |
| --- | ---: |
| FULL 48 kHz / 2 mic / queue depth 8 | {r['full']:,} |
| TINY 16 kHz / 1 mic / queue depth 4 | {r['tiny']:,} |

Machine-readable source: [`ci/resource-baseline.json`](../../ci/resource-baseline.json).
"""


def self_test() -> None:
    doc = build(80000, 50000, 28000, 1000, 32000, 5000)
    text = markdown(doc)
    assert "80,000" in text and "5,000" in text
    try:
        build(10, 20, 5, 1, 30, 3)
    except ValueError:
        pass
    else:
        raise AssertionError("ordering self-test did not fail")
    with tempfile.TemporaryDirectory(prefix="ap-resource-baseline-") as tmp:
        root = Path(tmp)
        (root / "baseline.json").write_text(json.dumps(doc, sort_keys=True), encoding="utf-8")
        assert json.loads((root / "baseline.json").read_text(encoding="utf-8"))["schema_version"] == 1
    print("resource baseline self-test: OK")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--self-test", action="store_true")
    parser.add_argument("--full", type=int)
    parser.add_argument("--low", type=int)
    parser.add_argument("--tiny", type=int)
    parser.add_argument("--raw", type=int)
    parser.add_argument("--runtime-full", type=int)
    parser.add_argument("--runtime-tiny", type=int)
    parser.add_argument("--json-output", type=Path)
    parser.add_argument("--markdown-output", type=Path)
    args = parser.parse_args()
    if args.self_test:
        self_test()
        return 0
    required = ("full", "low", "tiny", "raw", "runtime_full", "runtime_tiny", "json_output", "markdown_output")
    missing = [name for name in required if getattr(args, name) is None]
    if missing:
        parser.error("missing required arguments: " + ", ".join(missing))
    doc = build(args.full, args.low, args.tiny, args.raw, args.runtime_full, args.runtime_tiny)
    args.json_output.parent.mkdir(parents=True, exist_ok=True)
    args.markdown_output.parent.mkdir(parents=True, exist_ok=True)
    args.json_output.write_text(json.dumps(doc, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    args.markdown_output.write_text(markdown(doc), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
