#ifndef AUDIO_PIPELINE_AP_LIMITS_H
#define AUDIO_PIPELINE_AP_LIMITS_H

#include "audio_pipeline/audio_pipeline_build.h"
#include "ap_numeric.h"

#define AP_INTERNAL_RATE_MAX AP_BUILD_MAX_INTERNAL_RATE_HZ
#define AP_INTERNAL_FRAME_MAX AP_BUILD_INTERNAL_FRAME_MAX
#define AP_IO_FRAME_MAX AP_BUILD_IO_FRAME_MAX
#define AP_BUILD_MIC_CHANNEL_MAX AP_BUILD_MAX_MIC_CHANNELS

#endif
